version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=alfabank_test
      - MYSQL_USER=sergei
      - MYSQL_PASSWORD=mypassword